name: 🧪 Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run DOM specific tests
        run: bun run test:dom --reporter=junit --reporter-outfile=./junit-dom.xml

      - name: Run non-DOM specific tests
        run: bun run test:non-dom --reporter=junit --reporter-outfile=./junit-nondom.xml

      - name: Run closed-box tests (install playwright)
        run: bunx playwright install chromium

      - name: Run closed-box tests (actual test)
        run: bunx playwright test

      - name: Convert test report (JUnit to CTRF)
        run: bunx junit-to-ctrf "./junit-*.xml" --tool bun --o ctrf/ctrf-report-bun.json

      - name: Upload closed-box full test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

      - name: Combine test reports
        run: bunx ctrf merge ./ctrf

      - name: Test report
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: "./ctrf/*.json"
          suite-folded-report: true
          failed-folded-report: true

  build_release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Create artifact
        run: bun build --compile --outfile=subscription src/server.ts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: latest
          tag_name: latest
          files: subscription
          overwrite_files: true
          make_latest: "true"
          body: The latest version of the Subscription app
